package com.rong.seckill.dataobject;

import lombok.Data;

import javax.persistence.Entity;

@Data
@Entity
public class StockLog {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_log.stock_log_id
     *
     * @mbg.generated Mon Feb 25 23:42:11 CST 2019
     */
    private String stockLogId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_log.item_id
     *
     * @mbg.generated Mon Feb 25 23:42:11 CST 2019
     */
    private Integer itemId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_log.amount
     *
     * @mbg.generated Mon Feb 25 23:42:11 CST 2019
     */
    private Integer amount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_log.status
     *
     * @mbg.generated Mon Feb 25 23:42:11 CST 2019
     */
    private Integer status;
}